### ISSUE TITLE
Host Config Operator support for system settings changes & updates

### ISSUE THREAD

**Issue by sb1975** [airshipit/hostconfig-operator#1]
**Problem description (if applicable)**

As an operator I would like airshipctl to support the two use cases of updating system parameters of the individual machines which are part of the cluster via host config operator, so that I can make changes without having to deploy a new image & reboot.

This issues covers update system settings like sysctl, limits & permissions which are done through Diving Bell today. While these would normally be included in the image build, there may be scenarios where a more immediate update is required without deploying a new image.

Acceptance Criteria : 

1. Validate sysctl changes can be successfully applied via host config operator framework
2. Validate limits changes can be successfully applied via host config operator framework
3. Validate permission changes can be successfully applied via host config operator framework

**Comment by eak13** [comment]
Updates to scope based on 10/15 Design Call review captured here: https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0

**Comment by eak13** [comment]
@realsystem Stas, is there anything that needs discussion from a design perspective? On flight plan today, there was discussion whether or not we needed to put something on the design call agenda for 11/5.

**Comment by realsystem** [comment]
@ak3216 this task is only for validation. No need for any discussions.

**Comment by eak13** [comment]
@sirajyasin can you start looking at this?

**Comment by sirajyasin** [comment]
@ak3216  sure, I will start looking into this issue.

**Comment by sirajyasin** [comment]
@ak3216 , @sb1975 
From my initial analysis, the two parts mentioned in this issue are implemented
1. Ansible roles for sysctl, limit and permission exists
2. hostconfig-operator is deployed in treasuremap at initinfra-target phase.

Is there anything more to be done part of this issue like adding additional deployment scripts to validate Day2 operations using the above existing features ( sysctl, limit & permission ) of hostconfig-operator ?

**Comment by eak13** [comment]
Adding @jezogwza for his opinion. I think that might be a good idea to add some reference implementation scripts that provide examples as well as validation.

**Comment by sirajyasin** [comment]
@ak3216,  With further analysis i identified that Hostconfig operator is now deployed in treasuremap with zero inventory. So we need to inject SSH keys on the node for HC to manage them. I will try to continue working on the SSH part for the HC to have inventory list and manage those nodes.

**Comment by eak13** [comment]
@sirajyasin thanks for the update. Sounds like a good path forward.

**Comment by sirajyasin** [comment]
This PS (https://review.opendev.org/c/airship/airshipctl/+/774251) will enable ssh access to nodes after deployment. So we can use this for HCO to prepare ansible inventory.

**Comment by michaelfix** [comment]
@sreejithpunnapuzha is reviewing.  Testing locally, then plans to push a PS for review.

**Comment by michaelfix** [comment]
Update from @sreejithpunnapuzha -  Still testing.  Failed local testing where keys where not getting passed.  Under investigation.

**Comment by sreejithpunnapuzha** [comment]
change(https://review.opendev.org/c/airship/treasuremap/+/785090) is merged in treasuremap for enabling ssh

Verifying HCO is working as expected.

**Comment by sreejithpunnapuzha** [comment]
Change (v2 branch : https://review.opendev.org/c/airship/treasuremap/+/785554, v2.0 branch: https://review.opendev.org/c/airship/treasuremap/+/785612) adds the ssk-key secret for hostconfig-operator and the necessary steps needed to deploy HCO. have verified that HCO is working well.
