### ISSUE TITLE
Host Config Operator to provide periodic checks & validations

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#10]
Users will have the ability to define restrictions like package deny lists, permissions & limits. There is a need to have a process where Host Config Operator can periodically check against these restrictions, identify when they have been violated and ideally take corrective actions to fix.

**Comment by eak13** [comment]
@arvinderpal this was the topic discussed on 2/18 design call. Appreciate any insights into being able to schedule the operator.

**Comment by Arvinderpal** [comment]
I have a similar problem with the BMH <-> Node label sync. TL;DR some set of labels are managed by the label sync controller; however, someone may directly modify these labels on the worker Node -- we can't have this. We need a mechanism to periodically check that these Node labels are in sync with BMH labels. 

The pattern I'm using is to use `ctrl.Result{RequeueAfter: X}` to ensure periodic synchronization irrespective of any changes to the BMH. 
https://github.com/metal3-io/cluster-api-provider-metal3/pull/152/files#diff-e975c4d4f26e6963144942c06573d6a59cbad328230fa117a4e30cfe0de5ab78R191

**Comment by SirishaGopigiri** [comment]
We have reconcile annotation fields available as part of hostconfig-operator CR objects which help to run that particular CR periodically with the specified interval `ansible.operator-sdk/reconcile-period`.

For more info on reconcile configurations variables please refer here: https://github.com/airshipit/hostconfig-operator/blob/master/README.md#airship-hostconfig-operator-cr-object-specification-variables

Here is a simple HCO CR example with reconcile annotation: https://github.com/airshipit/hostconfig-operator/blob/master/demo_examples/example_reconcile.yaml#L9

Thank you!

**Comment by eak13** [comment]
@SirishaGopigiri thanks for the update. It sounds like we have a mechanism in place so @jezogwza, unless you have any issues, I'd say we can probably close this issue out as not needed.

**Comment by SirishaGopigiri** [comment]
@ak3216 sorry I didn't elaborate quite well. I meant that there is support to trigger any check/configuration periodically. But the support on how to check packages, permissions or limits should be added(either using shell commands or some scripts or some existing ansible modules). I think it would be good if we have a design discussion on this to see how this should be supported.

**Comment by eak13** [comment]
Ah, got it, @SirishaGopigiri. I'll add something to Thursday's design call to discuss. Thanks for clarifying.

**Comment by mattmceuen** [comment]
Now that we've identified a path forward, and Sirisha has pointed out an example configuration for this, how do we want to proceed with this issue @ak3216 ?  Call it complete?  Or, put it on hold until we have some "real" HostConfig CRs that we want to make recurring?  Either way I feel like the _ability_ to make HostConfigs periodic is probably good enough for Airship 2.0, and we could put it into practice as we craft more HostConfigs post-2.0.

**Comment by eak13** [comment]
I’m fine closing this out & once we have specific use case (maybe deny list is first), we can create specific issues for that

Andrew
