### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by seaneagan** [airshipit/hostconfig-operator#12]
**Problem description (if applicable)**
We currently have no release automation to:
* publish semver image tags to quay
* publish release notes

**Proposed change**
Add similar release automation to that of airshipctl/krm functions: https://github.com/airshipit/airshipctl/issues/354

**Comment by seaneagan** [comment]
https://review.opendev.org/c/airship/hostconfig-operator/+/784163

**Comment by eak13** [comment]
@seaneagan can we close this?

**Comment by seaneagan** [comment]
@ak3216 the release notes automation is not there yet

**Comment by eak13** [comment]
@seaneagan got it, thanks. We were making a pass at the v2.1 issues and wanted to check. Thanks.

**Comment by eak13** [comment]
Closing as not needed
