### ISSUE TITLE
Host Config Operator fails Clair scans for high risk vulnerabilities

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#13]
Describe the bug
Clair scans have identified a high risk vulnerability in Host Config Operator. See attached for details.
Update HCO & any underlying components to resolve the vulnerabilities.  

Steps To Reproduce
Run Clair scan against the images.

Expected Behavior
No high risk security vulnerabilities are found.
[hostconfig-operator-88e34e4-2021-05-28_18-03-00.txt](https://github.com/airshipit/hostconfig-operator/files/6591499/hostconfig-operator-88e34e4-2021-05-28_18-03-00.txt)

**Comment by SirishaGopigiri** [comment]
Please assign this to me

**Comment by SirishaGopigiri** [comment]
Size would be 'M'
