### ISSUE TITLE
Update hostconfig-operator base image

### ISSUE THREAD

**Issue by SirishaGopigiri** [airshipit/hostconfig-operator#14]
**Problem description (if applicable)**
The current base image(quay.io/operator-framework/ansible-operator:v0.17.0) is almost a year old.

**Proposed change**
Update it to latest version quay.io/operator-framework/ansible-operator:v1.8.0 or newer stable version at the time of fixing the issue.

**Potential impacts**
Some of the features may need re-coding or re-design
* Callback plugin
* We may get new security vulnerabilities in Clair

**Comment by gorshunovr** [comment]
WIP: https://review.opendev.org/c/airship/hostconfig-operator/+/800647

**Comment by pallavgupta** [comment]
pls assign it to me.

**Comment by sreejithpunnapuzha** [comment]
Above mentioned PS is wrong. Correct commit https://review.opendev.org/c/airship/hostconfig-operator/+/807945 is merged. hence closing this issue.
