### ISSUE TITLE
Host Config Operator to support Containerd & Docker updates/upgrades

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#2]
As an operator, I want the ability to push Containerd or Docker updates through Host Config Operator, so that I can make package or configuration updates without having to deploy a new image. 

While the typical path would be to include in a new image, there maybe situations like resolving a CVE which might call for a more immediate update without deploying a new image. 

There is one issue based on the assumption that the mechanism for pushing a Docker or Containerd update will be similar. This feature should support one and/or the other & does not imply that both will always be updated together. 

Source: https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0

**Comment by SirishaGopigiri** [comment]
Please assign it to me

**Comment by michaelfix** [comment]
@SirishaGopigiri  (Sirisha), do you have an updated status?  Thanks

**Comment by SirishaGopigiri** [comment]
Hi Mike
Here is a WIP PS: https://review.opendev.org/c/airship/hostconfig-operator/+/773389
Thank you
