### ISSUE TITLE
Host Config Operator to provide emergency package/binary installation/update capabilities

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#4]
As an operator, I want to be able to install or update system software packages leveraging host config operator, so that I have an emergency mechanism to make updates.

Typically, the normal path for updating packages would be through image builder & then deploying a new image with the updated package(s). However, there may be some urgent situations where a mechanism is needed to make updates on the fly without applying a new image.

Reference: https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0&fvid=115720849

**Comment by SirishaGopigiri** [comment]
Please assign to me

**Comment by eak13** [comment]
@SirishaGopigiri all yours, thanks!

**Comment by SirishaGopigiri** [comment]
PSs related to this issue

https://review.opendev.org/c/airship/hostconfig-operator/+/775332
https://review.opendev.org/c/airship/hostconfig-operator/+/773389

**Comment by SirishaGopigiri** [comment]
The PSs are merged can someone please close this issue, thank you!

**Comment by eak13** [comment]
Closing per patchset merges
