### ISSUE TITLE
Host Config Operator to provide ethtool support

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#5]
As an operator, I want to leverage host config operator to make ethtool supported network driver/hardware changes, so that I can make changes not requiring a reboot without having to deploy a new image.

Normally, network driver/hardware changes will be part of the image build/cloud init, but there may be scenarios ***need examples*** where host config operator can be leveraged to issue ethtool commands. This is supported by Diving Bell today.

Ethtool man page https://linux.die.net/man/8/ethtool
Reference: https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0&fvid=115720849

**Comment by sureshl** [comment]
Please assign this to me - Size L

**Comment by eak13** [comment]
@sureshl all yours. Thanks for the estimate as well!

**Comment by sureshl** [comment]
Related PS - https://review.opendev.org/c/airship/hostconfig-operator/+/785945

**Comment by SirishaGopigiri** [comment]
I think this is closed, the PS is merged. @sureshl can you confirm?

**Comment by sureshl** [comment]
> I think this is closed, the PS is merged. @sureshl can you confirm?

Yes, PS is merged.

**Comment by eak13** [comment]
Closing it out due to patchset merging.
