### ISSUE TITLE
Host Config Operator support for life cycling apparmor

### ISSUE THREAD

**Issue by eak13** [airshipit/hostconfig-operator#6]
As an operator, I want to leverage host config operator to manage apparmor life cycle, so that I can make updates/upgrades without having to deploy a new image.

While apparmor is something that would also be part of the image build, there may be scenarios where a more immediate apparmor change is needed without deploying a new image.

Reference: https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0&fvid=115720849

**Comment by sreejithpunnapuzha** [comment]
Commit (https://review.opendev.org/c/airship/hostconfig-operator/+/792868) with apparmor integration pushed to HCO repo

**Comment by sreejithpunnapuzha** [comment]
Commit (https://review.opendev.org/c/airship/hostconfig-operator/+/792868) has be merged. so closing this issue
