### ISSUE TITLE
Fix image publish job

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/hostconfig-operator#7]
The Zuul post job looks like it's succeeding based on the output found here: 
https://zuul.opendev.org/t/openstack/builds?job_name=airship-hostconfig-operator-publish-image  

However, the hostconfig-operator image hasn't been pushed to Quay as evidenced here:
https://quay.io/repository/airshipit/hostconfig-operator

This is causing subsequent issues in treasuremap as it is trying to pull the image from quay and failing because there isn't one there.

Please investigate & remediate so hostconfig-operator image is being pushed to quay.io.

**Comment by sreejithpunnapuzha** [comment]
image publish job have been fixed with this commit https://review.opendev.org/c/airship/hostconfig-operator/+/769973.
hostconfig-operator is now available in quay.io
